---
format:
  html: default
  pdf:
    geometry:
      - margin=0.65in
    fontsize: 10pt
    include-in-header:
      text: |
        \usepackage{enumitem}
        \setlist{nosep,leftmargin=*}
        \setlength{\parskip}{14pt}
        \setlength{\parindent}{0pt}
---

# Variables

## Problem 1: Variables of States

Suppose that the fifty states are the observational units. For each item, write **yes, it is a variable** or **no, it is not a variable**.

For each variable, report or make a reasonable guess for its value in your home state. For each item that is not a variable, briefly explain why.

**a)** The number of states that have a female governor

**b)** The percentage of the state's residents who are over 65 years of age

**c)** The highest speed limit in the state

**d)** Whether the state's name consists of one word

**e)** The average income of an adult resident of the state

**f)** The number of births per 1,000 residents of the state in 1999

**g)** The number of states that were settled before 1865

**h)** The average number of Congressional representatives per state

**i)** The number of Congressional representatives from the state

## Problem 2: Types of Variables

The observational units are 22 Broadway productions. Classify each variable from the supplied dataset as **quantitative** or **categorical**. If a categorical variable has exactly two possible values, also identify it as **binary**.

**a)** Production

**b)** Type

**c)** Gross

**d)** Attendance

**e)** Capacity

**f)** Top price

## Dataset: Broadway Productions

| Production | Type | Gross | Attendance | Capacity | Top price |
|---|---|--:|--:|--:|--:|
| Annie Get Your Gun | Musical | 572885 | 9892 | 12761 | 75 |
| Cabaret | Musical | 466670 | 6647 | 7360 | 90 |
| Cats | Musical | 350368 | 7200 | 11856 | 70 |
| Chicago | Musical | 536852 | 9664 | 11680 | 80 |
| Death of a Salesman | Play | 351082 | 6531 | 7483 | 75 |
| Epic Proportions | Play | 80379 | 2564 | 4776 | 65 |
| Footloose | Musical | 271022 | 6974 | 10784 | 75 |
| Fosse | Musical | 566644 | 8118 | 9128 | 80 |
| It Ain't Nothin' But The Blues | Musical | 88014 | 2366 | 5500 | 75 |
| Jekyll & Hyde | Musical | 283674 | 5613 | 8512 | 80 |
| Kat and the Kings | Musical | 108091 | 3218 | 8672 | 75 |
| Les Miserables | Musical | 375318 | 7677 | 11336 | 80 |
| Miss Saigon | Musical | 395522 | 8558 | 13945 | 80 |
| Ragtime | Musical | 420902 | 8913 | 14495 | 75 |
| Rent | Musical | 333248 | 6219 | 9448 | 80 |
| Side Man | Play | 106437 | 2894 | 6440 | 60 |
| Smokey Joe's Cafe | Musical | 168276 | 3547 | 9697 | 75 |
| The Lion King | Musical | 880717 | 14199 | 14032 | 80 |
| The Phantom of the Opera | Musical | 601218 | 9974 | 12856 | 80 |
| The Scarlet Pimpernel | Musical | 125597 | 2284 | 5464 | 80 |
| The Weir | Play | 120605 | 3450 | 7576 | 60 |
| Voices in the Dark | Play | 114607 | 3848 | 8688 | 60 |
